rethinkdb:
  image: rethinkdb:latest
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
  restart: always
  volumes:
    - "/srv/rethinkdb:/data"
  command: "rethinkdb --bind all --cache-size 2048"

adbd:
  image: sorccu/adb
  privileged: true
  ports:
    - "5037:5037"
  restart: always
  volumes:
    - "/dev/bus/usb:/dev/bus/usb"
stf-local:
  image: test1:latest
  links:
    - rethinkdb
    - adbd
  ports:
    - "7100:7100"
    - "7110:7110"
    - "7120:7120"
    - "7400-7500:7400-7500"
  restart: always
  command: ./open.sh
  #command: stf provider  --min-port 7400 --max-port 7700 --connect-sub tcp://192.168.1.104:7114 --connect-push tcp://192.168.1.104:7116 --group-timeout 20000  --storage-url http://192.168.1.104 --public-ip 192.168.1.104 --adb-host 192.168.1.102 --adb-port 5037


